/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/assets/icons/Arrow.svg')['default']
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    ChatList: typeof import('./src/components/chat/ChatList.vue')['default']
    ChatListItem: typeof import('./src/components/chat/ChatListItem.vue')['default']
    ChatWindow: typeof import('./src/components/chat/ChatWindow.vue')['default']
    ContactSidebar: typeof import('./src/components/chat/ContactSidebar.vue')['default']
    IconArrowDown: typeof import('~icons/icon/arrow-down')['default']
    IconIconInfoArrow: typeof import('~icons/icon/icon-info-arrow')['default']
    Info: typeof import('./src/assets/icons/Info.svg')['default']
    InfoMd: typeof import('./src/assets/icons/InfoMd.svg')['default']
    Loader: typeof import('./src/components/ui/Loader.vue')['default']
    MessageInput: typeof import('./src/components/message/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/message/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./src/assets/icons/Send.svg')['default']
    StatusIndicator: typeof import('./src/components/ui/StatusIndicator.vue')['default']
  }
}
