export const AUTO_REPLY_DELAY_MS_MIN = 1000
export const AUTO_REPLY_DELAY_MS_MAX = 2000

export const SIMULATE_OTHER_CHAT_DELAY_MS_MIN = 5000
export const SIMULATE_OTHER_CHAT_DELAY_MS_MAX = 10000

export const STATUS_UPDATE_INTERVAL_MS = 12000

export const MESSAGES_LOAD_DELAY_MS = 1500

export const SEND_MESSAGE_DELAY_MS_MIN = 1000
export const SEND_MESSAGE_DELAY_MS_MAX = 1500
